version: "3"

services:
  estimagus:
    image:
      estimagus
    build:
      context: ..
    ports:
      - 5000:5000
    environment:
      - SECRET_KEY=1234
      - DATA_DIR=data
    volumes:
      - ./data:/usr/src/app/data:z
